export const POST_TYPES = {
  GET_POSTS: 'GET_POSTS',
  CREATE_POST: 'CREATE_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  PENDING_POST: 'PENDING_POST',
  GET_POST_BY_ID: 'GET_POST_BY_ID',
  FULFILLED_POST: 'FULFILLED_POST',
  REJECTED_POST: 'REJECTED_POST'
};

export const USER_TYPES = {
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  LOGOUT: 'LOGOUT',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  ADD_USER_CURRENT: 'ADD_USER_CURRENT',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  UPLOAD_AVATAR: 'UPLOAD_AVATAR',
  PENDING_USER: 'PENDING_USER',
  FULFILLED_USER: 'FULFILLED_USER',
  REJECTED_USER: 'REJECTED_USER'
};

export const COMMENT_TYPES = {
  ADD_REPLY: 'ADD_REPLY'
};
